<?php

namespace App\Services;

use App\Repositories\PostRepository;
use App\Repositories\PageRepository;
use App\Repositories\CategoryRepository;
use App\Repositories\TagRepository;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\URL;

class SitemapService
{
    public function __construct(
        protected PostRepository $postRepository,
        protected PageRepository $pageRepository,
        protected CategoryRepository $categoryRepository,
        protected TagRepository $tagRepository
    ) {}

    /**
     * Generate sitemap XML
     */
    public function generate(): string
    {
        return Cache::remember('sitemap.xml', 3600, function () {
            $xml = '<?xml version="1.0" encoding="UTF-8"?>';
            $xml .= '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';

            // Homepage
            $xml .= $this->buildUrl(url('/'), now(), 'daily', '1.0');

            // Pages
            $pages = $this->pageRepository->getPublished();
            foreach ($pages as $page) {
                $xml .= $this->buildUrl(
                    url('/' . $page->slug),
                    $page->updated_at,
                    'weekly',
                    '0.8'
                );
            }

            // Posts
            $posts = $this->postRepository->getPublished();
            foreach ($posts as $post) {
                $xml .= $this->buildUrl(
                    url('/' . $post->slug),
                    $post->updated_at ?? $post->created_at,
                    'weekly',
                    '0.7'
                );
            }

            // Categories
            $categories = $this->categoryRepository->all();
            foreach ($categories as $category) {
                $xml .= $this->buildUrl(
                    get_term_link('category', $category),
                    $category->updated_at,
                    'weekly',
                    '0.6'
                );
            }

            // Tags
            $tags = $this->tagRepository->all();
            foreach ($tags as $tag) {
                $xml .= $this->buildUrl(
                    get_term_link('tag', $tag),
                    $tag->updated_at,
                    'monthly',
                    '0.5'
                );
            }

            // Blog archive
            $xml .= $this->buildUrl(url('/blog'), now(), 'daily', '0.9');

            $xml .= '</urlset>';

            return $xml;
        });
    }

    /**
     * Build single URL entry for sitemap
     */
    protected function buildUrl(string $loc, $lastmod, string $changefreq, string $priority): string
    {
        $xml = '<url>';
        $xml .= '<loc>' . htmlspecialchars($loc) . '</loc>';
        $xml .= '<lastmod>' . $lastmod->format('Y-m-d') . '</lastmod>';
        $xml .= '<changefreq>' . $changefreq . '</changefreq>';
        $xml .= '<priority>' . $priority . '</priority>';
        $xml .= '</url>';

        return $xml;
    }

    /**
     * Generate robots.txt content
     */
    public function generateRobotsTxt(): string
    {
        $content = "# Robots.txt for " . config('app.name') . "\n";
        $content .= "# Generated by VeCarCMS\n\n";

        // Check if indexing is allowed from settings
        $allowIndexing = settings('seo_allow_indexing', true);

        if ($allowIndexing) {
            $content .= "User-agent: *\n";
            $content .= "Allow: /\n";
            $content .= "Disallow: /admin/\n";
            $content .= "Disallow: /login\n";
            $content .= "Disallow: /register\n";
            $content .= "Disallow: /password/\n";
            $content .= "\n";
            
            // Add sitemap location
            $content .= "Sitemap: " . url('/sitemap.xml') . "\n";
        } else {
            // Block all robots
            $content .= "User-agent: *\n";
            $content .= "Disallow: /\n";
        }

        return $content;
    }

    /**
     * Clear sitemap cache
     */
    public function clearCache(): void
    {
        Cache::forget('sitemap.xml');
    }
}

